// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfPGfDJJculMEXAO5C0PenBM_oPi6rKI',
    appId: '1:816717361610:web:062bfcc41f48b157f69f33',
    messagingSenderId: '816717361610',
    projectId: 'airquality-tubes',
    authDomain: 'airquality-tubes.firebaseapp.com',
    storageBucket: 'airquality-tubes.firebasestorage.app',
    databaseURL:
        'https://airquality-tubes-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKkd_cJv1_D8PKshOY_d04F8YltQz7VJ8',
    appId: '1:816717361610:android:d89169ff8aee4fb4f69f33',
    messagingSenderId: '816717361610',
    projectId: 'airquality-tubes',
    authDomain: 'airquality-tubes.firebaseapp.com',
    storageBucket: 'airquality-tubes.firebasestorage.app',
    databaseURL:
        'https://airquality-tubes-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
