import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:iot_air_quality_monitoring/services/auth_service.dart';
import 'package:iot_air_quality_monitoring/services/monitoring_service.dart';
import 'package:iot_air_quality_monitoring/services/historical_data_service.dart';
import 'package:iot_air_quality_monitoring/utils/aqi_utils.dart';
import 'package:iot_air_quality_monitoring/models/sensor_data.dart';
import 'package:iot_air_quality_monitoring/models/historical_data.dart';
import 'package:iot_air_quality_monitoring/widgets/realtime_chart.dart'; // Pastikan file ini ada
import 'dart:async';
import 'history_screen.dart';
import 'settings_screen.dart';

class DashboardScreen extends StatefulWidget {
  const DashboardScreen({super.key});

  @override
  State<DashboardScreen> createState() => _DashboardScreenState();
}

class _DashboardScreenState extends State<DashboardScreen> {
  final MonitoringService _monitoringService = MonitoringService();
  final HistoricalDataService _historicalService = HistoricalDataService();
  final AuthService _authService = AuthService();
  Timer? _historyTimer;
  SensorData? _currentSensorData;

  // List lokal untuk menampung riwayat data sementara agar grafik bergerak
  final List<SensorData> _graphData = [];

  @override
  void initState() {
    super.initState();
    _startHistoryTimer();
  }

  @override
  void dispose() {
    _historyTimer?.cancel();
    super.dispose();
  }

  void _startHistoryTimer() {
    _historyTimer = Timer.periodic(const Duration(seconds: 10), (timer) {
      if (_currentSensorData != null) {
        _saveToHistory(_currentSensorData!);
      }
    });
  }

  Future<void> _saveToHistory(SensorData data) async {
    try {
      final historyData = HistoricalData(
        id: '', // Generated by Firebase
        coPpm: data.coPpm,
        dustDensity: data.dustDensity,
        temperature: data.temperature,
        humidity: data.humidity,
        timestamp: DateTime.now().millisecondsSinceEpoch ~/ 1000,
      );
      await _historicalService.addHistoricalData(historyData);
      // Debug: Show generic toast/snackbar to confirm save
      if (mounted) {
        // Enabled to verify saves are working:
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('✓ Saved to history!'), duration: Duration(milliseconds: 800)));
      }
    } catch (e) {
      debugPrint('Error saving history: $e');
      if (mounted) {
         ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Save failed: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Air Quality Dashboard'),
        backgroundColor: Theme.of(context).primaryColor,
        foregroundColor: Colors.white,
        elevation: 4,
        actions: [
          PopupMenuButton(
            icon: const Icon(Icons.more_vert),
            itemBuilder: (context) => [
              const PopupMenuItem(
                value: 'history',
                child: ListTile(
                  leading: Icon(Icons.history),
                  title: Text('History'),
                ),
              ),
              const PopupMenuItem(
                value: 'settings',
                child: ListTile(
                  leading: Icon(Icons.settings),
                  title: Text('Settings'),
                ),
              ),
              const PopupMenuItem(
                value: 'logout',
                child: ListTile(
                  leading: Icon(Icons.logout),
                  title: Text('Logout'),
                ),
              ),
            ],
            onSelected: (value) {
              if (value == 'history') {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const HistoryScreen(),
                  ),
                );
              } else if (value == 'settings') {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => const SettingsScreen(),
                  ),
                );
              } else if (value == 'logout') {
                _handleLogout();
              }
            },
          ),
        ],
      ),
      body: StreamBuilder<SensorData>(
        stream: _monitoringService.getMonitoringStream(),
        builder: (context, snapshot) {
          // --- LOGIKA MENYIMPAN DATA KE LIST GRAFIK ---
          if (snapshot.hasData) {
            final newData = snapshot.data!;
            _currentSensorData = newData;

            // Cek apakah data baru memiliki timestamp berbeda agar tidak duplikat
            // Jika list kosong, langsung masukkan.
            bool shouldAdd = false;
            if (_graphData.isEmpty) {
              shouldAdd = true;
            } else if (newData.timestamp != null &&
                _graphData.last.timestamp != newData.timestamp) {
              shouldAdd = true;
            }

            if (shouldAdd) {
              // Tambahkan ke list
              // Kita gunakan addPostFrameCallback agar tidak error "setState during build"
              // atau karena ini variabel lokal state biasa (bukan widget state terpisah),
              // modifikasi list langsung aman, tapi UI update ikut stream builder.
              _graphData.add(newData);

              // Batasi jumlah titik data (misal: 20 titik terakhir) agar memori hemat
              if (_graphData.length > 20) {
                _graphData.removeAt(0);
              }
            }
          }
          // ---------------------------------------------

          // Handling Loading & Error
          if (snapshot.connectionState == ConnectionState.waiting ||
              (snapshot.connectionState == ConnectionState.active &&
                  !snapshot.hasData)) {
            return const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 20),
                  Text('Loading air quality data...'),
                ],
              ),
            );
          } else if (snapshot.hasError) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.error_outline, size: 64, color: Colors.red),
                  const SizedBox(height: 16),
                  Text('Error: ${snapshot.error}', textAlign: TextAlign.center),
                  const SizedBox(height: 16),
                  ElevatedButton(
                    onPressed: () {
                      setState(() {});
                    },
                    child: const Text('Retry'),
                  ),
                ],
              ),
            );
          } else if (!snapshot.hasData) {
            return const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.data_usage_outlined, size: 64, color: Colors.grey),
                  SizedBox(height: 16),
                  Text('No data available', textAlign: TextAlign.center),
                ],
              ),
            );
          }

          final sensorData = snapshot.data!;
          final aqiStatus = AQIUtils.getAQIStatus(sensorData);
          final statusColor = AQIUtils.getStatusColor(aqiStatus);
          final statusText = AQIUtils.getStatusText(aqiStatus);
          final healthMessage = AQIUtils.getHealthMessage(aqiStatus);

          // Widget untuk menampilkan waktu pembaruan terakhir dengan gaya yang lebih baik
          Widget buildLastUpdated(SensorData sensorData) {
            String lastUpdatedText;
            if (sensorData.timestamp != null && sensorData.timestamp! > 0) {
              final dateTime = DateTime.fromMillisecondsSinceEpoch(
                sensorData.timestamp! * 1000,
              );
              lastUpdatedText =
                  'Last updated: ${DateFormat('MMM dd, yyyy - HH:mm:ss').format(dateTime)}';
            } else {
              lastUpdatedText = 'Last updated: --:--:--';
            }

            return Container(
              margin: const EdgeInsets.only(top: 8),
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
              decoration: BoxDecoration(
                color: Colors.grey.shade200,
                borderRadius: BorderRadius.circular(12),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(Icons.update, color: Colors.grey.shade700, size: 14),
                  const SizedBox(width: 6),
                  Text(
                    lastUpdatedText,
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.grey.shade700,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            );
          }

          // Gunakan SingleChildScrollView agar bisa scroll ke bawah melihat grafik
          return SingleChildScrollView(
            child: Column(
              children: [
                // 1. Header Status AQI
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(16.0),
                  decoration: BoxDecoration(
                    color: statusColor.withValues(alpha: 0.1),
                    border: Border(
                      bottom: BorderSide(
                        color: statusColor.withValues(alpha: 0.3),
                        width: 1,
                      ),
                    ),
                  ),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(
                            aqiStatus == AQIStatus.warning
                                ? Icons.warning_amber_rounded
                                : Icons.check_circle_rounded,
                            color: statusColor,
                            size: 28,
                          ),
                          const SizedBox(width: 12),
                          Text(
                            statusText,
                            style: TextStyle(
                              fontSize: 22,
                              fontWeight: FontWeight.bold,
                              color: statusColor,
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text(
                        healthMessage,
                        style: TextStyle(
                          fontSize: 16,
                          color: statusColor,
                          fontWeight: FontWeight.w500,
                        ),
                        textAlign: TextAlign.center,
                      ),
                      // Menggunakan widget yang sudah dibuat
                      buildLastUpdated(sensorData),
                    ],
                  ),
                ),

                // 2. Grid Kartu Sensor
                Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: GridView.count(
                    crossAxisCount: 2,
                    crossAxisSpacing: 16.0,
                    mainAxisSpacing: 16.0,
                    shrinkWrap:
                        true, // Penting agar tidak crash di dalam SingleChildScrollView
                    physics:
                        const NeverScrollableScrollPhysics(), // Scroll mengikuti parent
                    children: [
                      _buildSensorCard(
                        'CO (PPM)',
                        sensorData.coPpm.toStringAsFixed(2),
                        sensorData.coPpm > 100 ? Colors.red : Colors.blue,
                      ),
                      _buildSensorCard(
                        'Dust (mg/m³)',
                        sensorData.dustDensity.toStringAsFixed(2),
                        sensorData.dustDensity > 75 ? Colors.red : Colors.brown,
                      ),
                      _buildSensorCard(
                        'Temperature (°C)',
                        sensorData.temperature.toStringAsFixed(1),
                        Colors.orange,
                      ),
                      _buildSensorCard(
                        'Humidity (%)',
                        sensorData.humidity.toStringAsFixed(1),
                        Colors.cyan,
                      ),
                    ],
                  ),
                ),

                // 3. Bagian Grafik Real-time
                Padding(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 16.0,
                    vertical: 8.0,
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      const Text(
                        "Real-time Trends",
                        style: TextStyle(
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 16),

                      if (_graphData.isNotEmpty)
                        RealTimeChart(
                          dataPoints: List.from(_graphData),
                          title: "Temperature (°C)",
                          lineColor: Colors.orange,
                          parameter: 'temp',
                        ),
                      const SizedBox(height: 16),

                      if (_graphData.isNotEmpty)
                        RealTimeChart(
                          dataPoints: List.from(_graphData),
                          title: "Humidity (%)",
                          lineColor: Colors.cyan,
                          parameter: 'hum',
                        ),
                      const SizedBox(height: 16),

                      // Grafik CO
                      if (_graphData.isNotEmpty)
                        RealTimeChart(
                          dataPoints: List.from(
                            _graphData,
                          ), // Kirim copy list agar aman
                          title: "Carbon Monoxide (PPM)",
                          lineColor: Colors.blue,
                          parameter: 'co',
                        ),
                      const SizedBox(height: 16),

                      // Grafik Debu
                      if (_graphData.isNotEmpty)
                        RealTimeChart(
                          dataPoints: List.from(_graphData),
                          title: "Dust Density (mg/m³)",
                          lineColor: Colors.brown,
                          parameter: 'dust',
                        ),
                      const SizedBox(height: 30), // Padding bawah
                    ],
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _buildSensorCard(String title, String value, Color color) {
    return Card(
      elevation: 4,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: BorderSide(color: color.withValues(alpha: 0.3), width: 1),
      ),
      child: Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(16),
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              color.withValues(alpha: 0.05),
              color.withValues(alpha: 0.2),
            ],
          ),
        ),
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                title,
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: color,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 8),
              FittedBox(
                fit: BoxFit.scaleDown,
                child: Text(
                  value,
                  style: TextStyle(
                    fontSize: 26,
                    fontWeight: FontWeight.bold,
                    color: color,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _handleLogout() async {
    try {
      await _authService.signOut();
      if (mounted) {
        Navigator.of(context).pushReplacementNamed('/login');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error logging out: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }
}
